parameters:
  "service-dir":
    default: "sdk/databox"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}"
    azure-resource-provider-folder: "resource-manager"
    output-file: "{version-status}/{version}/databox.json"
    examples-dir: "{project-root}/examples"
    arm-types-dir: "{project-root}/../../../../common-types/resource-management"

    emit-lro-options: "all"
  "@azure-tools/typespec-csharp":
    flavor: azure
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
    clear-output-folder: true
    model-namespace: true
    namespace: "Azure.ResourceManager.DataBox"
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-databox"
    namespace: "azure.mgmt.databox"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-databox"
    namespace: "com.azure.resourcemanager.databox"
    service-name: "Data Box" # human-readable service name, whitespace allowed
    flavor: azure
    use-object-for-unknown: true
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/arm-databox"
    flavor: azure
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-databox"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/databox"
    emitter-output-dir: "{output-dir}/{service-dir}/armdatabox"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armdatabox"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-tools/typespec-powershell":
    service-dir: "src"
    package-dir: "DataBox/DataBox.Autorest"
    clear-output-folder: true
    azure: true
    module-version: 0.1.0
    prefix: 'Az'
    subject-prefix: 'DataBox'
    service-name: DataBox
    module-name: "{prefix}.{service-name}"
    exclude-tableview-properties:
      - Id
      - Type
    disable-transform-identity-type-for-operation:
      - Jobs_Update
    directive:
      - where:
          subject: Operation
        hide: true
      - where:
          parameter-name: SubscriptionId
        set:
          default:
            script: '(Get-AzContext).Subscription.Id'
      - where:
          variant: ^(Create|Update)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      - where:
          variant: ^CreateViaIdentity.*$
        remove: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
