parameters:
  "service-dir":
    default: "sdk/keyvault"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    omit-unreachable-types: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
    examples-dir: "{project-root}/examples"
    emit-lro-options: "all"
  "@azure-tools/typespec-csharp":
    flavor: azure
    emitter-output-dir: "{output-dir}/{service-dir}/Azure.ResourceManager.KeyVault"
    clear-output-folder: true
    model-namespace: true
    namespace: "Azure.ResourceManager.KeyVault"
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-keyvault"
    namespace: "azure.mgmt.keyvault"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-keyvault"
    namespace: "com.azure.resourcemanager.keyvault"
    service-name: "KeyVault" # human-readable service name, whitespace allowed
    flavor: azure
    enable-sync-stack: false
    premium: true
    customization-class: customization/src/main/java/KeyVaultCustomization.java
    uuid-as-string: false
    rename-model:
      TrackedResource: Resource
    client-side-validations: true
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/arm-keyvault"
    flavor: azure
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-keyvault"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/keyvault"
    emitter-output-dir: "{output-dir}/{service-dir}/armkeyvault"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armkeyvault/v2"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-tools/typespec-powershell":
    service-dir: "src"
    package-dir: "KeyVault/KeyVault.Autorest"
    clear-output-folder: true
    azure: true
    module-version: 0.1.0
    prefix: 'Az'
    subject-prefix: 'KeyVault'
    service-name: KeyVault
    module-name: "{prefix}.{service-name}"
    emit-modeler-output: true
    exclude-tableview-properties:
      - Id
      - Type
    disable-transform-identity-type-for-operation:
      - ManagedHsms_Update
    directive:
      - where:
          subject: Operation
        hide: true
      - where:
          parameter-name: SubscriptionId
        set:
          default:
            script: '(Get-AzContext).Subscription.Id'
      - where:
          variant: ^(Create|Update)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      - where:
          variant: ^CreateViaIdentity.*$
        remove: true
      - no-inline:  # choose ONE of these models to disable inlining
        - Error
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
