parameters:
  "service-dir":
    default: "sdk/mysql"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    omit-unreachable-types: true
    emitter-output-dir: "{project-root}"
    azure-resource-provider-folder: "resource-manager"
    output-file: "{version-status}/{version}/openapi.json"
    examples-dir: "{project-root}/examples"

    arm-types-dir: "{project-root}/../../../../common-types/resource-management"
    emit-lro-options: "all"
  "@azure-tools/typespec-csharp":
    flavor: azure
    package-name: "Azure.ResourceManager.MySql"
    namespace: "{package-name}.FlexibleServers"
    emitter-output-dir: "{output-dir}/{service-dir}/{package-name}"
    clear-output-folder: true
    model-namespace: true
    api-version: "2024-12-30"
  "@azure-tools/typespec-python":
    service-dir: "sdk/mysqlflexibleservers"
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-mysqlflexibleservers"
    namespace: "azure.mgmt.mysqlflexibleservers"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-mysqlflexibleserver"
    service-dir: "sdk/mysqlflexibleserver"
    namespace: "com.azure.resourcemanager.mysqlflexibleserver"
    service-name: "MySql"
    flavor: azure
    use-object-for-unknown: true
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/arm-mysql-flexible"
    flavor: azure
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-mysql-flexible"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/mysql"
    emitter-output-dir: "{output-dir}/{service-dir}/armmysqlflexibleservers"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armmysqlflexibleservers"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-tools/typespec-powershell":
    service-dir: "src"
    package-dir: "MySql/MySql.Autorest"
    clear-output-folder: true
    azure: true
    module-version: 0.1.0
    prefix: 'Az'
    subject-prefix: 'MySql'
    service-name: MySql
    module-name: "{prefix}.{service-name}"
    exclude-tableview-properties:
      - Id
      - Type
    directive:
      - where:
          subject: Operation
        hide: true
      - where:
          parameter-name: SubscriptionId
        set:
          default:
            script: '(Get-AzContext).Subscription.Id'
      - where:
          variant: ^(Create|Update)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      - where:
          variant: ^CreateViaIdentity.*$
        remove: true

linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
